# Generated by Django 5.0.1 on 2024-01-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'worker', 'verbose_name_plural': 'workers'},
        ),
        migrations.RemoveField(
            model_name='worker',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='job',
        ),
        migrations.AddField(
            model_name='worker',
            name='description_for_profil',
            field=models.TextField(default='Данный пользователь ничего о себе не написал, но мы уверены, что это очень хороший и позитивный человек, который скоро добьется финансовых успехов.', max_length=10000, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(default='images/nou.jpg', upload_to='images/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin role'), ('Special', 'Special role'), ('Custom', 'Custom role')], default='Custom', max_length=256),
        ),
    ]
