# Generated by Django 5.0.1 on 2024-01-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_worker_options_remove_worker_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin role'), ('Special', 'Special role'), ('Custom', 'Custom role'), ('SuperUser', 'SuperUser role')], default='Custom', max_length=256),
        ),
    ]
