# Generated by Django 3.2 on 2024-01-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_worker_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'worker', 'verbose_name_plural': 'workers'},
        ),
        migrations.AddField(
            model_name='worker',
            name='description_for_profil',
            field=models.TextField(default=('Данный пользоваетель ничего о себе не написал, ', 'но, мы уверене, что это очень хороший и позитивынй человек,', ' который скоро добьется финансовых успехов.'), max_length=10000, verbose_name='description'),
        ),
    ]
