# Generated by Django 3.2 on 2024-01-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240118_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(default='static/nou.jpg', upload_to='static/files', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='description_for_profil',
            field=models.TextField(default='Данный пользователь ничего о себе не написал, но мы уверены, что это очень хороший и позитивный человек, который скоро добьется финансовых успехов.', max_length=10000, verbose_name='description'),
        ),
    ]
