# Generated by Django 3.2.4 on 2024-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='text',
            field=models.TextField(default='Данный пользователь ничего о себе не написал, но мы уверены, что это очень хороший и позитивный человек, который скоро добьется финансовых успехов.', max_length=10000, verbose_name='Договоренность'),
        ),
    ]
