# Generated by Django 3.2 on 2024-01-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240118_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(default='/static/images/nou.jpg', upload_to='static/files', verbose_name='image'),
        ),
    ]
