# Generated by Django 3.2 on 2024-01-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(default='\\static\\images\nou.jpg', upload_to='static/files', verbose_name='image'),
        ),
    ]
