# Generated by Django 5.0.1 on 2024-01-19 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20240118_1847'),
        ('users', '0007_alter_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='balance',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='job.balance', verbose_name='balance'),
        ),
    ]
