# Generated by Django 5.0.1 on 2024-01-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20240118_1847'),
        ('users', '0008_alter_worker_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='job',
            field=models.ManyToManyField(default='безработный', related_name='job', to='job.job'),
        ),
    ]
