# Generated by Django 5.0.1 on 2024-01-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(default='images/nou.jpg', upload_to='images/', verbose_name='image'),
        ),
    ]
