# Generated by Django 5.0.1 on 2024-01-20 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20240118_1847'),
        ('users', '0014_alter_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='job.balance', verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='job',
            field=models.ManyToManyField(blank=True, null=True, related_name='job', to='job.job'),
        ),
    ]
