# Generated by Django 5.0.1 on 2024-01-28 19:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neural_network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max 256', max_length=256, unique=True, verbose_name='Название')),
                ('image', models.ImageField(default='images/network/default.jpg', upload_to='images/network/', verbose_name='Изображение')),
                ('description', models.TextField(default='Данный пользователь ничего о себе не написал, но мы уверены, что это очень хороший и позитивный человек, который скоро добьется финансовых успехов.', max_length=256, validators=[django.core.validators.MinLengthValidator(limit_value='40', message=('Минимум 40 символов',))], verbose_name='Описание')),
                ('url', models.URLField(max_length=256, verbose_name='Url адрес')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'neural network',
                'verbose_name_plural': 'neural networks',
                'ordering': ('date_joined',),
            },
        ),
        migrations.CreateModel(
            name='Other_Source_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Подработка')),
                ('discription', models.TextField(default='Дефолтное описание', max_length=10000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Другой ист дохода',
                'verbose_name_plural': 'Другие ист дохода',
                'db_table': 'Other_Source',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('id',), 'verbose_name': 'Основная мод работы', 'verbose_name_plural': 'Основные мод работы'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='busyness',
        ),
        migrations.RemoveField(
            model_name='job',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='payment',
        ),
        migrations.AddField(
            model_name='balance',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker_balance', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='discription',
            field=models.TextField(default='Дефолтное описание', max_length=10000, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default=1, max_length=256, unique=True, verbose_name='Работа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='amount_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='balance money'),
        ),
        migrations.AlterModelTable(
            name='job',
            table='Job',
        ),
        migrations.CreateModel(
            name='Job_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_in_money', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=1000000000, message='Не может быть больше 1000000000')], verbose_name='Оплата')),
                ('duration', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=30, message='Не может быть больше 1000000000')], verbose_name='сумма дней')),
                ('busyness', models.CharField(choices=[('Основная', 'Основная работа'), ('Подработка', 'Частичная занятость')], default='Подработка', max_length=256, verbose_name='Занятость')),
                ('total_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=1000000000, message='Не может быть больше 1000000000')], verbose_name='Общая сумма')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last_updated')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.job', verbose_name='работы')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'db_table': 'job_payment',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Network_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_in_money', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=1000000000, message='Не может быть больше 1000000000')], verbose_name='Оплата')),
                ('duration', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=30, message='Не может быть больше 1000000000')], verbose_name='сумма дней')),
                ('busyness', models.CharField(choices=[('Основная', 'Основная работа'), ('Подработка', 'Частичная занятость')], default='Подработка', max_length=256, verbose_name='Занятость')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last_updated')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='job.neural_network', verbose_name='нейросети')),
            ],
            options={
                'verbose_name': 'Нейросеть оплаты',
                'verbose_name_plural': 'Нейросети оплаты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Other_Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_in_money', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=1000000000, message='Не может быть больше 1000000000')], verbose_name='Оплата')),
                ('duration', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=30, message='Не может быть больше 1000000000')], verbose_name='сумма дней')),
                ('busyness', models.CharField(choices=[('Основная', 'Основная работа'), ('Подработка', 'Частичная занятость')], default='Подработка', max_length=256, verbose_name='Занятость')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last_updated')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_sources', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
                ('other_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_sources', to='job.other_source_model', verbose_name='другие источники')),
            ],
            options={
                'verbose_name': 'Другой источник оплаты',
                'verbose_name_plural': 'Другие источники оплаты',
                'ordering': ('id',),
            },
        ),
    ]
