# Generated by Django 5.0.1 on 2024-01-26 20:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neural_network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max 256', max_length=256, unique=True, verbose_name='Название')),
                ('image', models.ImageField(default='images/network/default.jpg', upload_to='images/network/', verbose_name='Изображение')),
                ('description', models.TextField(default='Обычное описание для нейросети', max_length=256, verbose_name='Описание')),
                ('url', models.URLField(max_length=256, verbose_name='Url адрес')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'neural network',
                'verbose_name_plural': 'neural networks',
                'ordering': ('date_joined',),
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('id',), 'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.AddField(
            model_name='balance',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker_balance', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default=1, max_length=256, unique=True, verbose_name='Название работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='amount_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='balance money'),
        ),
        migrations.AlterField(
            model_name='job',
            name='busyness',
            field=models.CharField(choices=[('Main', 'Main job'), ('Part-time', 'Part-time job')], default='Part-time', max_length=256, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.CharField(choices=[('Day', 'working time duration - day'), ('Month', 'working time duration - month')], default='Day', max_length=256, verbose_name='Оплата за определенный период'),
        ),
        migrations.AlterField(
            model_name='job',
            name='payment',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=1000000000, message='Не может быть больше 1000000000')], verbose_name='Оплата'),
        ),
        migrations.CreateModel(
            name='Job_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_in_money', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=1000000000, message='Не может быть больше 1000000000')], verbose_name='Оплата')),
                ('job', models.ManyToManyField(related_name='payments', to='job.job', verbose_name='Работа')),
            ],
        ),
    ]
