# Generated by Django 3.2 on 2024-01-18 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('name',), 'verbose_name': 'job', 'verbose_name_plural': 'jobs'},
        ),
        migrations.AlterField(
            model_name='job',
            name='payment',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=1000000000, message='Не может быть больше 1000000000')], verbose_name='payment'),
        ),
    ]
