# Generated by Django 5.0.1 on 2024-01-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_neural_network_other_source_model_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neural_network',
            name='description',
            field=models.TextField(default='Данный пользователь ничего о себе не написал, но мы уверены, что это очень хороший и позитивный человек, который скоро добьется финансовых успехов.', max_length=256, verbose_name='Описание'),
        ),
    ]
