# Generated by Django 3.2.4 on 2024-05-15 10:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_auto_20240515_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mandatory_expenses_model',
            new_name='Expenses_model',
        ),
        migrations.RemoveField(
            model_name='temporary_expenses_model',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='expenses_model',
            options={'ordering': ('id',), 'verbose_name': 'Таблица расходов'},
        ),
        migrations.AlterModelTable(
            name='expenses_model',
            table='Expenses_model',
        ),
        migrations.DeleteModel(
            name='Permanent_expenses_model',
        ),
        migrations.DeleteModel(
            name='Temporary_expenses_model',
        ),
    ]
