# Generated by Django 5.0.1 on 2024-01-30 20:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_neural_network_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_payment',
            name='duration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Не может быть меньше 0'), django.core.validators.MaxValueValidator(limit_value=30, message='Не может быть больше 1000000000')], verbose_name='сумма дней'),
        ),
        migrations.AlterField(
            model_name='job_payment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='network_payment',
            name='duration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Не может быть меньше 0'), django.core.validators.MaxValueValidator(limit_value=30, message='Не может быть больше 1000000000')], verbose_name='сумма дней'),
        ),
        migrations.AlterField(
            model_name='network_payment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='other_source',
            name='payment_in_money',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Не может быть меньше 0'), django.core.validators.MaxValueValidator(limit_value=1000000000, message='Не может быть больше 1000000000')], verbose_name='Оплата'),
        ),
    ]
