# Generated by Django 5.0.1 on 2024-01-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_payment_duration_alter_job_payment_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neural_network',
            name='description',
            field=models.TextField(default='Дефолтное описание', max_length=256, verbose_name='Описание'),
        ),
    ]
