# Generated by Django 3.2.4 on 2024-05-15 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_expenses_model_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses_model',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата'),
        ),
    ]
