# Generated by Django 5.0.1 on 2024-01-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_neural_network_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neural_network',
            name='image',
            field=models.ImageField(default='images/network/default_Uf.jpg', upload_to='images/network/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='neural_network',
            name='url',
            field=models.URLField(verbose_name='Url адрес'),
        ),
    ]
