# Generated by Django 5.0.1 on 2024-01-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_neural_network_image_alter_neural_network_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neural_network',
            name='title',
            field=models.CharField(error_messages={'unique': 'Название уже существует такое'}, help_text='Max 256', max_length=256, unique=True, verbose_name='Название'),
        ),
    ]
