# Generated by Django 3.2.4 on 2024-05-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20240515_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses_model',
            name='variety',
            field=models.CharField(default=1, max_length=256, verbose_name='Тип расхода'),
            preserve_default=False,
        ),
    ]
