# Generated by Django 3.2.4 on 2024-05-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20240516_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses_model',
            name='comment',
            field=models.CharField(default='Дефолтное описание для комментария', max_length=256, verbose_name='Комментарий'),
        ),
    ]
