# Generated by Django 5.0.1 on 2024-02-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_neural_network_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_payment',
            name='comment',
            field=models.TextField(default='Дефолтное описание', max_length=10000, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='network_payment',
            name='comment',
            field=models.TextField(default='Дефолтное описание', max_length=10000, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='other_source',
            name='comment',
            field=models.TextField(default='Дефолтное описание', max_length=10000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='job_payment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='network_payment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='other_source',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
