# Generated by Django 5.0.1 on 2024-02-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_job_payment_comment_network_payment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_payment',
            name='comment',
            field=models.TextField(default='Дефолтное описание для комментария', max_length=10000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='network_payment',
            name='comment',
            field=models.TextField(default='Дефолтное описание для комментария', max_length=10000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='other_source',
            name='comment',
            field=models.TextField(default='Дефолтное описание для комментария', max_length=10000, verbose_name='Комментарий'),
        ),
    ]
