# Generated by Django 5.0.1 on 2024-02-03 08:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_job_payment_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_source',
            name='duration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Не может быть меньше 0'), django.core.validators.MaxValueValidator(limit_value=30, message='Не может быть больше 1000000000')], verbose_name='сумма дней'),
        ),
        migrations.AlterField(
            model_name='other_source',
            name='payment_in_money',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=1000000000, message='Не может быть больше 1000000000')], verbose_name='Оплата'),
        ),
        migrations.CreateModel(
            name='Earning_scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название схемы')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url адрес площадки')),
                ('discription', models.TextField(default='Дефолтное описание', max_length=10000, verbose_name='Описание')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network', to='job.neural_network', verbose_name='нейросети')),
                ('other_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_source', to='job.other_source_model', verbose_name='другие источники')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Схема заработка',
                'verbose_name_plural': 'Схемы заработка',
                'db_table': 'Earning_scheme',
                'ordering': ('id',),
            },
        ),
    ]
