# Generated by Django 5.0.1 on 2024-02-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_other_source_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning_scheme',
            name='image',
            field=models.ImageField(default='images/money.jpg', upload_to='images/scheme/', verbose_name='Изображение'),
        ),
    ]
