# Generated by Django 3.2.4 on 2024-04-29 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0015_maling_model_сontacts_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maling_model',
            name='email',
            field=models.EmailField(error_messages={'unique': 'email существует уже'}, max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.CreateModel(
            name='Crypto_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(default='Дефолтное описание', max_length=10000, verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Модель криптовалюты',
                'verbose_name_plural': 'Модели криптовалют',
                'db_table': 'Crypto_model',
                'ordering': ('id',),
            },
        ),
    ]
