# Generated by Django 3.2.4 on 2024-05-07 08:46

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_auto_20240429_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_model',
            name='course',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не может быть меньше 1'), django.core.validators.MaxValueValidator(limit_value=1000000000, message='Не может быть больше 1000000000')], verbose_name='Общая сумма'),
        ),
        migrations.AddField(
            model_name='crypto_model',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto_model',
            name='image',
            field=models.ImageField(default='images/money.jpg', upload_to='images/crypto/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='crypto_model',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='crypto_model',
            name='title',
            field=models.CharField(default=121, max_length=256, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto_model',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url адрес площадки'),
        ),
    ]
