# Файл main.yml
# Имя workflow
name: Main site_job Workflow
# Перечень событий-триггеров, при которых должен запускаться workflow
on:
  # Событие push возникает,
  # когда изменения исходного кода приходят на сервер GitHub
  push:
    # Отслеживаем изменения только в ветке main
    branches:
      - main
      - master
      - server/site
      - feature/update_all
# Перечень задач
jobs:
  # Единственная задача — склонировать код 
  # и вывести в консоль дерево файлов
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      # На GitHub Actions есть готовые описания шагов, 
      # их можно использовать в своих workflow.
      # Применим готовое описание шага для получения исходного кода
      - name: Check out repository code  # Имя шага задаём сами
        uses: actions/checkout@v3  # Берём готовое решение из библиотеки GitHub Actions
      # Выполняем команду tree в текущей директории
      - name: Print project tree
        run: tree .
      - name: Set up Python
        uses: actions/setup-python@v4
      # В action setup-python@v4 передаём параметр — версию Python
        with:
          python-version: 3.9
      # Обновляем pip, устанавливаем flake8 и flake8-isort, 
      # устанавливаем зависимости проекта
      - name: Install dependencies
        env:
          STEP_NAME: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r requirements.txt

      - name: Test with flake8
        env:
          STEP_NAME: Test with flake8  
        run: python -m flake8 .

      - name: Django tests
        env:
          STEP_NAME: Django tests
        run: |
          python manage.py test
          cd max_site
          pytest

      - name: Send message on failure
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Ошибка деплоя! Не пройден пункт: ${{ steps.1.conclusion }}. ${{ github.actor }} создал коммит:
            Сообщение коммита: ${{ github.event.commits[0].message }}
            Репозиторий: ${{ github.repository }}
            Посмотреть изменения: https://github.com/${{ github.repository }}/commit/${{github.sha}}
        if: ${{ failure() }}
      - name: Send message on success
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Деплой успешно выполнен! ${{ github.actor }} создал коммит:
            Сообщение коммита: ${{ github.event.commits[0].message }}
            Репозиторий: ${{ github.repository }}
            Посмотреть изменения: https://github.com/${{ github.repository }}/commit/${{github.sha}}
        if: ${{ success() }}